
- name: reload systemd configuration
  become: yes
  systemd:
    daemon_reload: true

# Restart service and ensure it is enabled
- name: restart logstash
  become: yes
  service: name=logstash state=restarted enabled=yes
  register: logstash_restarted
