# ----------------------------------------------------------------------------
# Start elasticsearch
# ----------------------------------------------------------------------------
---

- name: Restart logstash
  systemd:
      name: 'logstash'
      state: restarted
  become: true