# ----------------------------------------------------------------------------
# Start elasticsearch
# ----------------------------------------------------------------------------
---

- name: Restart logstash
  service:
    name: 'logstash'
    state: restarted
  become: true